version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/filip/courses/docker_kubernetes/frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/filip/courses/docker_kubernetes/frontend:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "test"]
    restart: on-failure
